### ISSUE TITLE
How to create translation of Arizen

### ISSUE THREAD

**Issue by neduchal** [ZencashOfficial/arizen#173]
# We would like to have these translations:
With bounty **0.2 ZEN / translation** (only if your translation will be without corrections and you will be only one contributor - see bounty requirements):
- [x] Mandarin #179 (2x @evanslify)
- [x] Spanish #180 (@sdaylor, @arrobarabito, @DetrikSyS)
- [ ] Hindi #181
- [x] Arabic #182 (@sdaylor)
- [x] Portuguese #183 (@sdaylor)
- [ ] Bengali #184
- [x] Russian #185 (@saintolexiy)
- [x] Japanese #186 (@v2tmobile, @t-ikuta)
- [ ] Punjabi #187
- [x] German #178 (@Awarrior91, @sdaylor)
- [x] Korean #188 (Jonghun_Korea, UTC+9 from Discord)
- [x] French #189 (@sdaylor, @Kernel4, @slauzon1)

Without bounty:
- [x] Others #190 (English, Czech, #228 Polish, #215 Dutch, #225 Greek, Serbian, Turkish, #238 Vietnamese)

# Translation instructions
Minimum supported version: 1.1.2 

All language files are save in subdirectory **lang**. They have fixed filename: **lang_{langcode}.json** (e.g. lang_en.json for English.)

Each language file has same structure which begins with languageName and languageValue items. For English translation ther _languageName_ item is **English** and _languageValue_ is **en** (notice: same as langcode in filename).

The rest of the lang file are translated items grouped as they are grouped in the Arizen.

For new translation it is necessary to create **new lang_{langcode}.json** file (please use [this 2 character language ISO 639-1 Code](https://www.loc.gov/standards/iso639-2/php/code_list.php)). The best way is to **[copy english version](https://github.com/ZencashOfficial/arizen/blob/development/app/lang/lang_en.json) and change name to wanted language**. Then you have to change values of all keys in the language file. 

### Notes: 
- Some strings contain tags such as  **&lt;strong&gt;** or **%s**. Please do not delete or make any changes of this tags. Just translate the rest of the string.
- Parts labeled as **login** and **createWallet** are optional. This pages of the Arizen app will be translated in future. 

### Example (shows only a part of the lang file):
English lang:
```
{
  "languageName": "English",
  "languageValue": "en",
  "wallet": {
    "showSettingsDialogButton" : "Settings",
    "showAboutDialogButton" : "About",
    "refreshWallet" : "Refresh",
    "logout" : "Logout",
  }
}
```
Czech translation
```
{
  "languageName": "Czech",
  "languageValue": "cs",
  "wallet": {
    "showSettingsDialogButton" : "Nastavení",
    "showAboutDialogButton" : "O Programu",
    "refreshWallet" : "Obnovit",
    "logout" : "Odhlásit",
  }
}
```

# Bounty requirements:

1. Create a pull request to **development branch** (PR) with translation (only translations from the list above will be credited)
2. Only first contributor will be credited (if there isn't any other)
3. Refer your PR in this issue and in relevant one for record
4. When there will be more contributors - e.g. translation corrections, the bounty will be divided equally among all participants who made a contribution to that PR.

**Comment by LukasBures** [comment]
#177 partial Polish translation

**Comment by gwandre** [comment]
Can i help with "Portuguese #183"?

**Comment by LukasBures** [comment]
@gwandre yes sure, but please wait, we will announce it after all code will be ready and then you can start to translate

**Comment by gwandre** [comment]
Nice, thanks. Would be great to work with this.

**Comment by PizzaPete** [comment]
#215 Dutch translation and a fix for the English translation.

**Comment by LukasBures** [comment]
Let's start ...

**Comment by sdaylor** [comment]
Added Spanish localization in pull request #222

**Comment by sdaylor** [comment]
Added Arabic localization in pull request #226

**Comment by LukasBures** [comment]
Thank you very much. We will wait up to 4 days and if nobody will have any adjustment we can merge this, then I will ask you for your T address.

**Comment by evanslify** [comment]
Added Traditional Chinese & Simplified Chinese localization in #227

**Comment by sdaylor** [comment]
Added German translation in #229

**Comment by LukasBures** [comment]
👍

**Comment by sdaylor** [comment]
Portuguese translation in #232

**Comment by t-ikuta** [comment]
Improved the Japanese translation (PR #235)

**Comment by v2tmobile** [comment]
Vietnamese translation in PR #238

**Comment by LukasBures** [comment]
Bounty for merged translations.

Post here your T address where you want to send the bounty:
- [ ] Mandarin #179 (2x @evanslify) = 2x 0.2 = 0.4 ZEN
- [ ] Spanish #180 (@sdaylor, @arrobarabito, @DetrikSyS) = 0.06666666 ZEN each
- [ ] Russian #185 (@saintolexiy) = 0.2 ZEN
- [ ] Japanese #186 (@v2tmobile, @t-ikuta) = 0.1 ZEN each
- [ ] German #178 (@Awarrior91, @sdaylor) = 0.1 ZEN each
- [ ] French #189 (@sdaylor, @Kernel4, @slauzon1) = 0.06666666 ZEN each

**Comment by saintolexiy** [comment]
znfizhrVh9N6gETrhhbTxYgkT2y7hUcygCC

**Comment by Awarrior91** [comment]
znVRARh6CKs16xjFGTKjd2Wy73QDgNbfyin

Thanks :)

**Comment by sdaylor** [comment]
zng6tyFAHMTcijBz9xrBT1okEcw5SxAv5cF

**Comment by v2tmobile** [comment]
znoP42WWFXWkFQfeNe5XZx5CRG5TMopXNA9

Thanks, ZenCash!

**Comment by slauzon1** [comment]
znnDj6q7ZP7K5inrDVx5Qh5av9VDiJGmCeR

Thank you ZenCash :)

**Comment by DetrikSyS** [comment]
zna2MKw7czxBjBrmVqvXXdvspU7oDJmPvXK

**Comment by Kernel4** [comment]
znXpJEJ2zLrv8ZzKh9hdpFK7Qv5v7H7E35C

Thank you Zencash :) !

Le 16 janv. 2018 00:36, "Antonio Morillo" <notifications@github.com> a
écrit :

**Comment by evanslify** [comment]
Hello. Please send to `znVPUqJB5rwq6XVsicRTJ2tnuacCmFxipPW`. Thank you for creating Arizen!

**Comment by arrobarabito** [comment]
Hello!
znVYRK9tSvDzpanjQKybPgLijtig7LY2CHW
Thanks ZEN team.

**Comment by LukasBures** [comment]
@t-ikuta please send your T-address you are the last :-)

**Comment by LukasBures** [comment]
OK, I have got it on Discord.

**Comment by LukasBures** [comment]
Bounty for merged translations.

Post here your T address where you want to send the bounty:

- [ ] Arabic #182 (@sdaylor) = 0.2 ZEN
- [ ] Portuguese #183 (@sdaylor) = 0.2 ZEN
- [ ] Korean #188 (Jonghun_Korea, UTC+9 from Discord) = 0.2 ZEN

**Comment by sdaylor** [comment]
zng6tyFAHMTcijBz9xrBT1okEcw5SxAv5cF
Thanks!

**Comment by caratzky** [comment]
Can I do the Tagalog Translation for this project? In ISO 639-1, it is coded as 'tl'. I'll be waiting for your feedback. Thank you.

Best Regards, Caratzky

**Comment by LukasBures** [comment]
@caratzky hey, sure you can, but your language fit into "other" section = without a bounty.

**Comment by caratzky** [comment]
@LukasBures  don't worry, I'm only after of the Utopian-io rewards. Shall I start it now?

**Comment by LukasBures** [comment]
Yes sure 👍

**Comment by caratzky** [comment]
Done the translation, please check. Is there no other files due for
translation?

**Comment by codygee237** [comment]
Can I help with Cebuano Translation for this project? In ISO 639-2, it is coded as "ceb", hoping for your response. Thank you Sir.

**Comment by LukasBures** [comment]
It is not actual no longer, the translations will be needed for v2.0.0.
