### ISSUE TITLE
High-Level Specification and Roadmap for Arizen Development 2018

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#304]
Hey all,

I would like to use this issue for tracking long-term goals for Arizen project. This will be only high-level insight what we are going to implement (not how or when). This is continuing of this #72 high-level specification.

- [x] Domain fronting implementation when you use API for sending T transactions (on/off option). Implementation of b01291abfc98363c27b0abffa733830156792351 has been 
included in v1.1.5 release.
- [ ] We are going to update Arizen UX/UI experience. Arizen should be easy to use for users, so there is plenty of space how to improve that. The discussion here #298 (in progress)
- [x] Arizen has the possibility to connect via encrypted SSH connection directly to your zen-daemon on your own ZEN Secure Node (SN)  or common ZEN daemon running somewhere else. So it allows SN owners process Z transactions which are offloaded to SN. It has been implemented in #322 included from v1.1.7 release.
- [ ] The final step of this progress is allowing the user to set up their SNs only on one click. You can see my [SecurityNodeOneClickInstallation](https://github.com/LukasBures/SecurityNodeOneClickInstallation) scripts which works great for me.
- [ ] We are planning to add features for maintaining SN, e.g. one-click-update (when a new version of tracker SW or daemon will be released).
- [ ] We are still planning to add support for Trezor T and/or Ledger Nano S HW wallets. Which will store all your PKs for T and Z addresses. 

# Nice to have:
- [ ] Send amount in local currency eg. USD (it automatically show and send amount recalculated in ZENs).
- [x] Auto log-off (enable and set the time in settings), after X minute (minimum 1min) automatically log-off. Has been implemented in v1.1.6 version, #317.
- [ ] Add “pin” which you will have to put in before every transaction is sent out.
- [x] Change password. Has been implemented in v1.1.6 version, #317.
- [x] Add option to add user's RSA private key to connect Security Node, #348. 
- [x] Split a single large balance into several addresses with the same amount, e.g. 42 ZEN, #348. 
- [ ] Funding node balances in multiple Z-addresses for challenges

**Comment by LukasBures** [comment]
- [x] Add option to add user's RSA private key to connect Security Node, #348. 
- [x] Split a single large balance into several addresses with the same amount, e.g. 42 ZEN, #348. 

Completed

**Comment by zennermac** [comment]
Now that Sphere By Horizen is available we will be updating Arizen by exception.
Any non-complete actions in this issue will likely not be implemented as a priority.
Hardware wallet functionality such as ledger seed restore is being developed for Sphere By Horizen
